name: shyheads_customer_app
description: A full fledged shop & delivery system that contains four apps build in Flutter with an API built in PHP.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.1.1
  auto_size_text: ^3.0.0
  barcode_scan2: ^4.1.3
  community_material_icon: ^5.9.55
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^13.0.0
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^2.0.0
  fluttertoast: ^8.0.7
  folding_cell: ^1.0.2
  font_awesome_flutter: ^10.3.0
  geolocator: ^9.0.2
  get: ^4.1.4
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.0.6
  google_nav_bar: ^5.0.5
  image_picker: ^0.8.0+4
  intl: ^0.18.0
  pin_code_fields: ^7.2.0
  shimmer: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
